# Nivel global de logs
log4j.rootLogger=WARN, console

# Appender consola
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%-5p] %c - %m%n

# SILENCIAR o apagar por completo el wire log
log4j.logger.org.apache.hc.client5.http.wire=OFF

# También sube el nivel de todo el HttpClient 5
log4j.logger.org.apache.hc.client5.http=ERROR
log4j.logger.org.apache.hc.core5.http=ERROR

# En caso de HttpClient 4.x
log4j.logger.org.apache.http=ERROR
log4j.logger.org.apache.http.wire=OFF

# WebDriverManager
log4j.logger.io.github.bonigarcia.wdm=ERROR